// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol JcNativeApi {
  /// Logs the client in with the specified app account number and name.
  ///
  /// [appAccountNumber] is the app account number to log in with.
  ///
  /// [name] is the name to log in with.
  ///
  /// Returns `true` if the login was started successfully, `false` otherwise.
  func login(appAccountNumber: String, name: String) throws -> Bool
  /// Joins the specified conference.
  ///
  /// [conferenceID] is the ID of the conference to join.
  ///
  /// [password] is the password of the conference to join.
  ///
  /// Returns `true` if the conference was joined successfully, `false` otherwise.
  ///
  /// The client must be logged in before calling this method. See [login].
  func joinConference(conferenceID: String, password: String) throws -> Bool
  /// Initiates a call to the specified user.
  ///
  /// [userID] is the user ID of the user to call.
  ///
  /// [video] is whether the call should be a video call.
  ///
  /// Returns `true` if the call was initiated successfully, `false` otherwise.
  ///
  /// The client must be logged in before calling this method. See [login].
  func call(userID: String, video: Bool) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class JcNativeApiSetup {
  /// The codec used by JcNativeApi.
  /// Sets up an instance of `JcNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: JcNativeApi?) {
    /// Logs the client in with the specified app account number and name.
    ///
    /// [appAccountNumber] is the app account number to log in with.
    ///
    /// [name] is the name to log in with.
    ///
    /// Returns `true` if the login was started successfully, `false` otherwise.
    let loginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JcNativeApi.login", binaryMessenger: binaryMessenger)
    if let api = api {
      loginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appAccountNumberArg = args[0] as! String
        let nameArg = args[1] as! String
        do {
          let result = try api.login(appAccountNumber: appAccountNumberArg, name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loginChannel.setMessageHandler(nil)
    }
    /// Joins the specified conference.
    ///
    /// [conferenceID] is the ID of the conference to join.
    ///
    /// [password] is the password of the conference to join.
    ///
    /// Returns `true` if the conference was joined successfully, `false` otherwise.
    ///
    /// The client must be logged in before calling this method. See [login].
    let joinConferenceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JcNativeApi.joinConference", binaryMessenger: binaryMessenger)
    if let api = api {
      joinConferenceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let conferenceIDArg = args[0] as! String
        let passwordArg = args[1] as! String
        do {
          let result = try api.joinConference(conferenceID: conferenceIDArg, password: passwordArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      joinConferenceChannel.setMessageHandler(nil)
    }
    /// Initiates a call to the specified user.
    ///
    /// [userID] is the user ID of the user to call.
    ///
    /// [video] is whether the call should be a video call.
    ///
    /// Returns `true` if the call was initiated successfully, `false` otherwise.
    ///
    /// The client must be logged in before calling this method. See [login].
    let callChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.JcNativeApi.call", binaryMessenger: binaryMessenger)
    if let api = api {
      callChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIDArg = args[0] as! String
        let videoArg = args[1] as! Bool
        do {
          let result = try api.call(userID: userIDArg, video: videoArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      callChannel.setMessageHandler(nil)
    }
  }
}
